### ISSUE TITLE
Add the PDF file to the Github releases

### ISSUE THREAD

**Issue by jonohayon** [calcmogul/controls-engineering-in-frc#11]
So it seems as if [tavsys.net](http://tavsys.net) is down, and there's no way to download this amazing book. If possible, could the final PDF file be uploaded to the releases page on Github?

**Comment by calcmogul** [comment]
I considered doing GitHub releases in the past. I decided against it because I've been doing a release for every commit (every commit is deployable after all). At this point, there are over 700 releases (1.5 days per release for the last three years).

**Comment by jonohayon** [comment]
If you'd want to, I could maybe help setup TravisCI on a specific tag or something like that

**Comment by calcmogul** [comment]
I already have an Azure pipeline set up for PR and master builds (see azure-pipelines.yml), but the master publish pipeline I made in the GUI doesn't work yet; it's supposed to scp the pdf onto file.tavsys.net, but that's broken for some reason related to auth. I'm considering migrating to GitHub Actions because configuring everything in YAML seems easier.
